language: generic

dist: trusty
sudo: required

matrix:
    include:
    - os: linux
      compiler: gcc
      env: GCC_VERSION=7
        - CC=gcc-7
        - CXX=g++-7
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'deadsnakes']
          packages: ['g++-7', 'python3.5']
          addons:

before_install:
  - wget https://raw.githubusercontent.com/onqtam/doctest/master/doctest/doctest.h
  - sudo mv ./doctest.h /usr/local/include/doctest.h
  - export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"

install:
  - sudo apt-get install python3-pip python3-dev
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
  - sudo pip3 install numpy
  - sudo pip3 install scipy
  - sudo pip3 install --upgrade pip
  - sudo pip3 install tensorflow
  - sudo pip3 install h5py
  - sudo pip3 install keras
  - git clone https://github.com/Dobiasd/FunctionalPlus
  - cd FunctionalPlus
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  - git clone https://github.com/eigenteam/eigen-git-mirror
  - cd eigen-git-mirror
  - mkdir -p build && cd build
  - cmake ..
  - make
  - sudo make install
  - sudo ln -s /usr/local/include/eigen3/Eigen /usr/local/include/Eigen
  - cd ../..
  - git clone https://github.com/nlohmann/json
  - cd json
  - mkdir -p build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  - mkdir -p build && cd build
  - cmake .. -DFDEEP_BUILD_UNITTEST=ON

script:
  - which $CXX
  - $CXX --version
  - cmake --build . --target unittest --config Release --
